------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- NOTE: ~/.config/hypr/monique/monitors.lua holds the layout generated by Monique
-- (https://github.com/ToRvaLDz/monique).
 require("monique.monitors")
