-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8C44",
  mode = "1920x1200@60",
  position = "0x0",
  scale = 1,
})

hl.monitor({
  output = "desc:AOC 24G2W1G3- WUBP6HA006205",
  mode = "1920x1080@60",
  position = "0x-1080",
  scale = 1,
})
